### ISSUE TITLE
Windows build: Pdb API call failed, error code '3': solution

### ISSUE THREAD

**Issue by ZmeiGorynych** [udacity/FCND-Controls-CPP#9]
When trying to build this on windows in VS Community 2019, I got the above error. Could fix it by following Ben Baker's solution in the below link:

https://developercommunity.visualstudio.com/content/problem/552999/fatal-error-c1090-pdb-api-call-failed-error-code-3.html

Hope that is useful to others.

**Comment by friedrico** [comment]
For those who can or dont want to access the page:

**Solution - Ben Baker**
> For those getting the issue with vc142.pdb try setting "Configuration Properties->C/C++->Output Files->Program Database File Name" to "$(TEMP)vc$(PlatformToolsetVersion).pdb"
> 
> It could also work for the other pdb's by setting "Configuration Properties->Linker->Debugger->Generate Program Database File" to "$(TEMP)$(TargetName).pdb".
> 
> My best guess is the files are being locked by mspdbsrv.exe due to parallel compilation.
